[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
collateral_vault = "4MUbwAXCAZXPxZ8fU9SDv5TDsCA2EmrojJaXjZVMbwNy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
createVaultAta = "npx ts-node scripts/createVaultAta.ts"
demo = "npx ts-node scripts/demo.ts"
deposit = "npx ts-node scripts/deposit.ts"
derive = "npx ts-node scripts/derive.ts"
initAuthority = "npx ts-node scripts/initVaultAuthority.ts"
initVault = "npx ts-node scripts/initVault.ts"
lock = "npx ts-node scripts/lock.ts"
setup = "npx ts-node scripts/setup.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
transfer = "npx ts-node scripts/transfer.ts"
unlock = "npx ts-node scripts/unlock.ts"
withdraw = "npx ts-node scripts/withdraw.ts"

[hooks]

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
