[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
collateral_vault = "CqYzY3dRdbEBUg29TFBWXLrQQhumMeyRr6vJv76RNiTq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
derive = "npx ts-node scripts/derive.ts"
createVaultAta = "npx ts-node scripts/createVaultAta.ts"
initVault = "npx ts-node scripts/initVault.ts"
deposit = "npx ts-node scripts/deposit.ts"
withdraw = "npx ts-node scripts/withdraw.ts"

[hooks]

[test]
startup_wait = 10000